run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(go-rest-api-example)
  
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: "io/ioutil is deprecated, use io and os packages instead"
  
  gocyclo:
    min-complexity: 15
  
  lll:
    line-length: 120
  
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - lll
    - path: docs/
      linters:
        - lll