run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - exhaustive
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(go-rest-api-example)
  
  golint:
    min-confidence: 0.8
  
  gocyclo:
    min-complexity: 15
  
  lll:
    line-length: 120
  
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - lll
    - path: docs/
      linters:
        - lll